import { MovieItem } from '../../movies.model';
import { PaginatedMovieResponse, RemoteMovieResponse } from '../../movies.api';

export const MOVIEDB_REMOTE_RESPONSE: RemoteMovieResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/oNoprEND25zXR6Fns8cIZUkuoMc.jpg',
      genre_ids: [35, 80, 18],
      id: '308266',
      original_language: 'en',
      original_title: 'War Dogs',
      overview:
        "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
      popularity: 61.115,
      poster_path: '/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg',
      release_date: '2016-08-17',
      title: 'War Dogs',
      video: false,
      vote_average: 6.9,
      vote_count: 3948,
    },
    {
      adult: false,
      backdrop_path: '/kILQ61VAEl4UlTsFGajKmrVQT75.jpg',
      genre_ids: [10751, 35],
      id: '10992',
      original_language: 'en',
      original_title: 'Cats & Dogs',
      overview:
        'When a professor develops a vaccine that eliminates human allergies to dogs, he unwittingly upsets the fragile balance of power between cats and dogs and touches off an epic battle for pet supremacy. The fur flies as the feline faction, led by Mr. Tinkles, squares off against wide-eyed puppy Lou and his canine cohorts.',
      popularity: 42.177,
      poster_path: '/77dmCJelVTBPBwbTppiisQx0e82.jpg',
      release_date: '2001-07-04',
      title: 'Cats & Dogs',
      video: false,
      vote_average: 5.4,
      vote_count: 1344,
    },
    {
      adult: false,
      backdrop_path: '/of1EpT8iYFfiF1b0Bo3PPHjyAzi.jpg',
      genre_ids: [35, 10751],
      id: '22949',
      original_language: 'en',
      original_title: 'Old Dogs',
      overview:
        "Charlie and Dan have been best friends and business partners for thirty years; their Manhattan public relations firm is on the verge of a huge business deal with a Japanese company. With two weeks to sew up the contract, Dan gets a surprise: a woman he married on a drunken impulse nearly nine years before (annulled the next day) shows up to tell him he's the father of her twins, now seven, and she'll be in jail for 14 days for a political protest. Dan volunteers to keep the tykes, although he's up tight and clueless. With Charlie's help is there any way they can be dad and uncle, meet the kids' expectations, and still land the account?",
      popularity: 31.149,
      poster_path: '/kBGqhumfOuDCpIErICWPHcXNvah.jpg',
      release_date: '2009-11-24',
      title: 'Old Dogs',
      video: false,
      vote_average: 5.5,
      vote_count: 603,
    },
    {
      adult: false,
      backdrop_path: '/g6R1OT7ETBLGLeUJOE0pOiAFHcI.jpg',
      genre_ids: [80, 53],
      id: '500',
      original_language: 'en',
      original_title: 'Reservoir Dogs',
      overview:
        'A botched robbery indicates a police informant, and the pressure mounts in the aftermath at a warehouse. Crime begets violence as the survivors -- veteran Mr. White, newcomer Mr. Orange, psychopathic parolee Mr. Blonde, bickering weasel Mr. Pink and Nice Guy Eddie -- unravel.',
      popularity: 30.179,
      poster_path: '/AjTtJNumZyUDz33VtMlF1K8JPsE.jpg',
      release_date: '1992-09-02',
      title: 'Reservoir Dogs',
      video: false,
      vote_average: 8.1,
      vote_count: 12014,
    },
    {
      adult: false,
      backdrop_path: '/t22fWbzdnThPseipsdpwgdPOPCR.jpg',
      genre_ids: [35, 28],
      id: '726739',
      original_language: 'en',
      original_title: 'Cats & Dogs 3: Paws Unite',
      overview:
        "It's been ten years since the creation of the Great Truce, an elaborate joint-species surveillance system designed and monitored by cats and dogs to keep the peace when conflicts arise. But when a tech-savvy villain hacks into wireless networks to use frequencies only heard by cats and dogs, he manipulates them into conflict and the worldwide battle between cats and dogs is BACK ON. Now, a team of inexperienced and untested agents will have to use their old-school animal instincts to restore order and peace between cats and dogs everywhere.",
      popularity: 61.37,
      poster_path: '/4BgSWFMW2MJ0dT5metLzsRWO7IJ.jpg',
      release_date: '2020-10-02',
      title: 'Cats & Dogs 3: Paws Unite',
      video: false,
      vote_average: 6.5,
      vote_count: 165,
    },
    {
      adult: false,
      backdrop_path: '/gfwMVCtYjn4VjAQyIZ5bOj6KSu0.jpg',
      genre_ids: [35, 10751, 12],
      id: '11888',
      original_language: 'en',
      original_title: 'Snow Dogs',
      overview: "When a Miami dentist inherits a team of sled dogs, he's got to learn the trade or lose his pack to a crusty mountain man.",
      popularity: 21.993,
      poster_path: '/8DDC6z1XyLSiNLzKw1pXcYeAOJ3.jpg',
      release_date: '2002-01-18',
      title: 'Snow Dogs',
      video: false,
      vote_average: 5.7,
      vote_count: 619,
    },
    {
      adult: false,
      backdrop_path: '/jB5zHG1eHh0OC1S61itXNApZlLD.jpg',
      genre_ids: [12, 35, 16],
      id: '399174',
      original_language: 'en',
      original_title: 'Isle of Dogs',
      overview:
        "In the future, an outbreak of canine flu leads the mayor of a Japanese city to banish all dogs to an island that's a garbage dump. The outcasts must soon embark on an epic journey when a 12-year-old boy arrives on the island to find his beloved pet.",
      popularity: 26.285,
      poster_path: '/c0nUX6Q1ZB0P2t1Jo6EeFSVnOGQ.jpg',
      release_date: '2018-03-23',
      title: 'Isle of Dogs',
      video: false,
      vote_average: 7.9,
      vote_count: 3925,
    },
    {
      adult: false,
      backdrop_path: '/lajJKmazOSfJ6kPXVFxjr0JBDf0.jpg',
      genre_ids: [18, 53],
      id: '64639',
      original_language: 'en',
      original_title: 'Straw Dogs',
      overview:
        'L.A. screenwriter David Sumner relocates with his wife, Amy, to her hometown in the deep South. There, while tensions build between them, a brewing conflict with locals becomes a threat to them both.',
      popularity: 15.214,
      poster_path: '/hSW5Msz5Cr6vUQxChPSPdxufnss.jpg',
      release_date: '2011-09-16',
      title: 'Straw Dogs',
      video: false,
      vote_average: 5.8,
      vote_count: 430,
    },
    {
      adult: false,
      backdrop_path: '/uTfdOozort4sp9kukWxEmdmRsqJ.jpg',
      genre_ids: [16, 12, 35],
      id: '416153',
      original_language: 'en',
      original_title: 'Arctic Dogs',
      overview:
        'Animals band together to save the day when the evil Otto Von Walrus hatches a sinister scheme to accelerate global warming and melt the Arctic Circle.',
      popularity: 16.024,
      poster_path: '/5YHjyjd2N0ZXcnGuB8G1nIa6h9t.jpg',
      release_date: '2019-11-01',
      title: 'Arctic Dogs',
      video: false,
      vote_average: 6.2,
      vote_count: 102,
    },
    {
      adult: false,
      backdrop_path: '/8dDOhuTmMOwhwTFiAL2BhVkVCAq.jpg',
      genre_ids: [80, 18, 53],
      id: '994',
      original_language: 'en',
      original_title: 'Straw Dogs',
      overview:
        "David Sumner, a mild-mannered academic from the United States, marries Amy, an Englishwoman. In order to escape a hectic stateside lifestyle, David and his wife relocate to the small town in rural Cornwall where Amy was raised. There, David is ostracized by the brutish men of the village, including Amy's old flame, Charlie. Eventually the taunts escalate, and two of the locals rape Amy. This sexual assault awakes a shockingly violent side of David.",
      popularity: 15.068,
      poster_path: '/yigkfHE1OhkxPPrjrV78Y9ibGEk.jpg',
      release_date: '1971-12-23',
      title: 'Straw Dogs',
      video: false,
      vote_average: 7.2,
      vote_count: 714,
    },
    {
      adult: false,
      backdrop_path: '/pk1zexoUCtjFs761W48QyIPzwCj.jpg',
      genre_ids: [12, 80, 10751, 35],
      id: '425148',
      original_language: 'en',
      original_title: 'Show Dogs',
      overview:
        'Max, a macho, solitary Rottweiler police dog is ordered to go undercover as a primped show dog in a prestigious Dog Show, along with his human partner, to avert a disaster from happening.',
      popularity: 13.724,
      poster_path: '/2dvxCBUfDG2cAdkA921rERxhtcp.jpg',
      release_date: '2018-05-18',
      title: 'Show Dogs',
      video: false,
      vote_average: 6.1,
      vote_count: 205,
    },
    {
      adult: false,
      backdrop_path: '/hovfur18TPFABZIuJYvgjLpln8V.jpg',
      genre_ids: [35, 10751],
      id: '15189',
      original_language: 'en',
      original_title: 'Hotel for Dogs',
      overview:
        "Placed in a foster home that doesn't allow pets, 16-year-old Andi and her younger brother, Bruce, turn an abandoned hotel into a home for their dog. Soon other strays arrive, and the hotel becomes a haven for every orphaned canine in town. But the kids have to do some quick thinking to keep the cops off their tails.",
      popularity: 16.356,
      poster_path: '/maFnSOpmNDhlEYjOrnWrriJLF3T.jpg',
      release_date: '2009-01-16',
      title: 'Hotel for Dogs',
      video: false,
      vote_average: 6.1,
      vote_count: 737,
    },
    {
      adult: false,
      backdrop_path: '/rKOzBCXwtRtkLpDQOyCcNvDS0qo.jpg',
      genre_ids: [18],
      id: '35796',
      original_language: 'en',
      original_title: 'Lawn Dogs',
      overview:
        'In the affluent, gated community of Camelot Gardens, bored wives indiscriminately sleep around while their unwitting husbands try desperately to climb the social ladder. Trent, a 21-year-old outsider who mows the neighborhood lawns, quietly observes the infidelities and hypocrisies of this overly privileged society. When Devon, a 10-year-old daughter from one family, forges a friendship with Trent, things suddenly get very complicated.',
      popularity: 8.779,
      poster_path: '/9uas3iUGZI3cw0UQzC8H6lDbfru.jpg',
      release_date: '1997-11-21',
      title: 'Lawn Dogs',
      video: false,
      vote_average: 7.3,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [80, 18, 53],
      id: '443129',
      original_language: 'en',
      original_title: 'Reservoir Dogs',
      overview:
        'Short film made with the help of the Sundance Film Institute and serving as a proof-of-concept for the subsequent feature film.',
      popularity: 8.207,
      poster_path: '/xiPVdfcSO5P5wQcSzAwtMwBlvJ6.jpg',
      release_date: '1991-06-01',
      title: 'Reservoir Dogs',
      video: false,
      vote_average: 7.4,
      vote_count: 136,
    },
    {
      adult: false,
      backdrop_path: '/l8yf1Rfp58GGjt39R2jpo8nEshF.jpg',
      genre_ids: [35, 10751, 28, 14, 12, 9648],
      id: '39691',
      original_language: 'en',
      original_title: 'Cats & Dogs: The Revenge of Kitty Galore',
      overview:
        'The ongoing war between the canine and feline species is put on hold when they join forces to thwart a rogue cat spy with her own sinister plans for conquest.',
      popularity: 27.22,
      poster_path: '/nTsZT66I4U3aS9ezLdOKacfvo8T.jpg',
      release_date: '2010-07-28',
      title: 'Cats & Dogs: The Revenge of Kitty Galore',
      video: false,
      vote_average: 5.2,
      vote_count: 520,
    },
    {
      adult: false,
      backdrop_path: '/6PkzgNLKoK1Oy0j7L79JuBgl22r.jpg',
      genre_ids: [18, 36],
      id: '8588',
      original_language: 'en',
      original_title: 'Shooting Dogs',
      overview:
        'Two westerners, a priest and a teacher find themselves in the middle of the Rwandan genocide and face a moral dilemna. Do they place themselves in danger and protect the refugees, or escape the country with their lives? Based on a true story.',
      popularity: 6.213,
      poster_path: '/9xC2yUgqPVvoHykYuigrxLyunya.jpg',
      release_date: '2006-03-08',
      title: 'Shooting Dogs',
      video: false,
      vote_average: 7.5,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: '/kqkYa0ou7qRur7qb3QBfQkDA8wc.jpg',
      genre_ids: [10749, 35],
      id: '11648',
      original_language: 'en',
      original_title: 'Must Love Dogs',
      overview:
        "Sarah Nolan is a newly divorced woman cautiously rediscovering romance with the enthusiastic but often misguided help of her well-meaning family. As she braves a series of hilarious disastrous mismatches and first dates, Sarah begins to trust her own instincts again and learns that, no matter what, it's never a good idea to give up on love.",
      popularity: 10.667,
      poster_path: '/252PdRj3y2S05DC4oSf2qk2vva3.jpg',
      release_date: '2005-07-21',
      title: 'Must Love Dogs',
      video: false,
      vote_average: 5.9,
      vote_count: 393,
    },
    {
      adult: false,
      backdrop_path: '/bfZrLxmHh7jAvTJcnj5FX5J9yIW.jpg',
      genre_ids: [18, 35],
      id: '403068',
      original_language: 'en',
      original_title: 'Sun Dogs',
      overview:
        'A man eager to serve his country but rejected by the Marines pairs up with a young runaway to form an unlikely team on a misguided adventure.',
      popularity: 6.614,
      poster_path: '/hiEHsguMwMyZMRXgjgQaB2Vpbzj.jpg',
      release_date: '2017-06-18',
      title: 'Sun Dogs',
      video: false,
      vote_average: 6.8,
      vote_count: 75,
    },
    {
      adult: false,
      backdrop_path: '/tebcp0UUNmLui8kHhqozp3TmEqq.jpg',
      genre_ids: [35, 10749, 10770],
      id: '298317',
      original_language: 'en',
      original_title: "My Boyfriends' Dogs",
      overview:
        "The owners of a small diner are surprised one rainy evening when, just after close, a young woman wearing a wedding dress with three dogs in tow begs to come into their restaurant. What follows is the young woman's retelling of how she arrived at this curious junction in her life and how, through the search for the right man, she ended up as a runaway bride with three new dogs.",
      popularity: 6.479,
      poster_path: '/ffNqpSglkigE2eIVFGSXUYihFCN.jpg',
      release_date: '2014-10-18',
      title: "My Boyfriends' Dogs",
      video: false,
      vote_average: 6,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: '/6V5Jui7BiMHMr1ZIFmiFzefCzjd.jpg',
      genre_ids: [18, 16, 10751, 35, 14],
      id: '11497',
      original_language: 'en',
      original_title: 'All Dogs Go to Heaven',
      overview:
        "When a casino owning dog named Charlie is murdered by his rival Carface, he finds himself in Heaven basically by default since all dogs go to heaven. However, since he wants to get back at his killer, he cons his way back to the living with the warning that doing that damns him to Hell. Once back, he teams with his old partner, Itchy to prep his retaliation. He also stumbles on to an orphan girl who can talk to the animals, thus allowing him to get the inside info on the races to ensure his wins to finance his plans. However, all the while, he is still haunted by nightmares on what's waiting for him on the other side unless he can prove that he is worthy of Heaven again.",
      popularity: 16.63,
      poster_path: '/nmWh1NglDinfkHD9zCNqGWyhl7Q.jpg',
      release_date: '1989-11-17',
      title: 'All Dogs Go to Heaven',
      video: false,
      vote_average: 6.7,
      vote_count: 827,
    },
  ],
  total_pages: 30,
  total_results: 586,
};

export const PAGINATED_RESPONSE: PaginatedMovieResponse = {
  pagination: {
    currentPage: 1,
    total: 586,
    lastPage: 30,
    perPage: 20,
    start: 0,
    end: 20,
  },
  list: [
    {
      adult: false,
      backdrop_path: '/oNoprEND25zXR6Fns8cIZUkuoMc.jpg',
      genre_ids: [35, 80, 18],
      id: '308266',
      original_language: 'en',
      original_title: 'War Dogs',
      overview:
        "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
      popularity: 61.115,
      poster_path: '/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg',
      release_date: '2016-08-17',
      title: 'War Dogs',
      video: false,
      vote_average: 6.9,
      vote_count: 3948,
    },
    {
      adult: false,
      backdrop_path: '/kILQ61VAEl4UlTsFGajKmrVQT75.jpg',
      genre_ids: [10751, 35],
      id: '10992',
      original_language: 'en',
      original_title: 'Cats & Dogs',
      overview:
        'When a professor develops a vaccine that eliminates human allergies to dogs, he unwittingly upsets the fragile balance of power between cats and dogs and touches off an epic battle for pet supremacy. The fur flies as the feline faction, led by Mr. Tinkles, squares off against wide-eyed puppy Lou and his canine cohorts.',
      popularity: 42.177,
      poster_path: '/77dmCJelVTBPBwbTppiisQx0e82.jpg',
      release_date: '2001-07-04',
      title: 'Cats & Dogs',
      video: false,
      vote_average: 5.4,
      vote_count: 1344,
    },
    {
      adult: false,
      backdrop_path: '/of1EpT8iYFfiF1b0Bo3PPHjyAzi.jpg',
      genre_ids: [35, 10751],
      id: '22949',
      original_language: 'en',
      original_title: 'Old Dogs',
      overview:
        "Charlie and Dan have been best friends and business partners for thirty years; their Manhattan public relations firm is on the verge of a huge business deal with a Japanese company. With two weeks to sew up the contract, Dan gets a surprise: a woman he married on a drunken impulse nearly nine years before (annulled the next day) shows up to tell him he's the father of her twins, now seven, and she'll be in jail for 14 days for a political protest. Dan volunteers to keep the tykes, although he's up tight and clueless. With Charlie's help is there any way they can be dad and uncle, meet the kids' expectations, and still land the account?",
      popularity: 31.149,
      poster_path: '/kBGqhumfOuDCpIErICWPHcXNvah.jpg',
      release_date: '2009-11-24',
      title: 'Old Dogs',
      video: false,
      vote_average: 5.5,
      vote_count: 603,
    },
    {
      adult: false,
      backdrop_path: '/g6R1OT7ETBLGLeUJOE0pOiAFHcI.jpg',
      genre_ids: [80, 53],
      id: '500',
      original_language: 'en',
      original_title: 'Reservoir Dogs',
      overview:
        'A botched robbery indicates a police informant, and the pressure mounts in the aftermath at a warehouse. Crime begets violence as the survivors -- veteran Mr. White, newcomer Mr. Orange, psychopathic parolee Mr. Blonde, bickering weasel Mr. Pink and Nice Guy Eddie -- unravel.',
      popularity: 30.179,
      poster_path: '/AjTtJNumZyUDz33VtMlF1K8JPsE.jpg',
      release_date: '1992-09-02',
      title: 'Reservoir Dogs',
      video: false,
      vote_average: 8.1,
      vote_count: 12014,
    },
    {
      adult: false,
      backdrop_path: '/t22fWbzdnThPseipsdpwgdPOPCR.jpg',
      genre_ids: [35, 28],
      id: '726739',
      original_language: 'en',
      original_title: 'Cats & Dogs 3: Paws Unite',
      overview:
        "It's been ten years since the creation of the Great Truce, an elaborate joint-species surveillance system designed and monitored by cats and dogs to keep the peace when conflicts arise. But when a tech-savvy villain hacks into wireless networks to use frequencies only heard by cats and dogs, he manipulates them into conflict and the worldwide battle between cats and dogs is BACK ON. Now, a team of inexperienced and untested agents will have to use their old-school animal instincts to restore order and peace between cats and dogs everywhere.",
      popularity: 61.37,
      poster_path: '/4BgSWFMW2MJ0dT5metLzsRWO7IJ.jpg',
      release_date: '2020-10-02',
      title: 'Cats & Dogs 3: Paws Unite',
      video: false,
      vote_average: 6.5,
      vote_count: 165,
    },
    {
      adult: false,
      backdrop_path: '/gfwMVCtYjn4VjAQyIZ5bOj6KSu0.jpg',
      genre_ids: [35, 10751, 12],
      id: '11888',
      original_language: 'en',
      original_title: 'Snow Dogs',
      overview: "When a Miami dentist inherits a team of sled dogs, he's got to learn the trade or lose his pack to a crusty mountain man.",
      popularity: 21.993,
      poster_path: '/8DDC6z1XyLSiNLzKw1pXcYeAOJ3.jpg',
      release_date: '2002-01-18',
      title: 'Snow Dogs',
      video: false,
      vote_average: 5.7,
      vote_count: 619,
    },
    {
      adult: false,
      backdrop_path: '/jB5zHG1eHh0OC1S61itXNApZlLD.jpg',
      genre_ids: [12, 35, 16],
      id: '399174',
      original_language: 'en',
      original_title: 'Isle of Dogs',
      overview:
        "In the future, an outbreak of canine flu leads the mayor of a Japanese city to banish all dogs to an island that's a garbage dump. The outcasts must soon embark on an epic journey when a 12-year-old boy arrives on the island to find his beloved pet.",
      popularity: 26.285,
      poster_path: '/c0nUX6Q1ZB0P2t1Jo6EeFSVnOGQ.jpg',
      release_date: '2018-03-23',
      title: 'Isle of Dogs',
      video: false,
      vote_average: 7.9,
      vote_count: 3925,
    },
    {
      adult: false,
      backdrop_path: '/lajJKmazOSfJ6kPXVFxjr0JBDf0.jpg',
      genre_ids: [18, 53],
      id: '64639',
      original_language: 'en',
      original_title: 'Straw Dogs',
      overview:
        'L.A. screenwriter David Sumner relocates with his wife, Amy, to her hometown in the deep South. There, while tensions build between them, a brewing conflict with locals becomes a threat to them both.',
      popularity: 15.214,
      poster_path: '/hSW5Msz5Cr6vUQxChPSPdxufnss.jpg',
      release_date: '2011-09-16',
      title: 'Straw Dogs',
      video: false,
      vote_average: 5.8,
      vote_count: 430,
    },
    {
      adult: false,
      backdrop_path: '/uTfdOozort4sp9kukWxEmdmRsqJ.jpg',
      genre_ids: [16, 12, 35],
      id: '416153',
      original_language: 'en',
      original_title: 'Arctic Dogs',
      overview:
        'Animals band together to save the day when the evil Otto Von Walrus hatches a sinister scheme to accelerate global warming and melt the Arctic Circle.',
      popularity: 16.024,
      poster_path: '/5YHjyjd2N0ZXcnGuB8G1nIa6h9t.jpg',
      release_date: '2019-11-01',
      title: 'Arctic Dogs',
      video: false,
      vote_average: 6.2,
      vote_count: 102,
    },
    {
      adult: false,
      backdrop_path: '/8dDOhuTmMOwhwTFiAL2BhVkVCAq.jpg',
      genre_ids: [80, 18, 53],
      id: '994',
      original_language: 'en',
      original_title: 'Straw Dogs',
      overview:
        "David Sumner, a mild-mannered academic from the United States, marries Amy, an Englishwoman. In order to escape a hectic stateside lifestyle, David and his wife relocate to the small town in rural Cornwall where Amy was raised. There, David is ostracized by the brutish men of the village, including Amy's old flame, Charlie. Eventually the taunts escalate, and two of the locals rape Amy. This sexual assault awakes a shockingly violent side of David.",
      popularity: 15.068,
      poster_path: '/yigkfHE1OhkxPPrjrV78Y9ibGEk.jpg',
      release_date: '1971-12-23',
      title: 'Straw Dogs',
      video: false,
      vote_average: 7.2,
      vote_count: 714,
    },
    {
      adult: false,
      backdrop_path: '/pk1zexoUCtjFs761W48QyIPzwCj.jpg',
      genre_ids: [12, 80, 10751, 35],
      id: '425148',
      original_language: 'en',
      original_title: 'Show Dogs',
      overview:
        'Max, a macho, solitary Rottweiler police dog is ordered to go undercover as a primped show dog in a prestigious Dog Show, along with his human partner, to avert a disaster from happening.',
      popularity: 13.724,
      poster_path: '/2dvxCBUfDG2cAdkA921rERxhtcp.jpg',
      release_date: '2018-05-18',
      title: 'Show Dogs',
      video: false,
      vote_average: 6.1,
      vote_count: 205,
    },
    {
      adult: false,
      backdrop_path: '/hovfur18TPFABZIuJYvgjLpln8V.jpg',
      genre_ids: [35, 10751],
      id: '15189',
      original_language: 'en',
      original_title: 'Hotel for Dogs',
      overview:
        "Placed in a foster home that doesn't allow pets, 16-year-old Andi and her younger brother, Bruce, turn an abandoned hotel into a home for their dog. Soon other strays arrive, and the hotel becomes a haven for every orphaned canine in town. But the kids have to do some quick thinking to keep the cops off their tails.",
      popularity: 16.356,
      poster_path: '/maFnSOpmNDhlEYjOrnWrriJLF3T.jpg',
      release_date: '2009-01-16',
      title: 'Hotel for Dogs',
      video: false,
      vote_average: 6.1,
      vote_count: 737,
    },
    {
      adult: false,
      backdrop_path: '/rKOzBCXwtRtkLpDQOyCcNvDS0qo.jpg',
      genre_ids: [18],
      id: '35796',
      original_language: 'en',
      original_title: 'Lawn Dogs',
      overview:
        'In the affluent, gated community of Camelot Gardens, bored wives indiscriminately sleep around while their unwitting husbands try desperately to climb the social ladder. Trent, a 21-year-old outsider who mows the neighborhood lawns, quietly observes the infidelities and hypocrisies of this overly privileged society. When Devon, a 10-year-old daughter from one family, forges a friendship with Trent, things suddenly get very complicated.',
      popularity: 8.779,
      poster_path: '/9uas3iUGZI3cw0UQzC8H6lDbfru.jpg',
      release_date: '1997-11-21',
      title: 'Lawn Dogs',
      video: false,
      vote_average: 7.3,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [80, 18, 53],
      id: '443129',
      original_language: 'en',
      original_title: 'Reservoir Dogs',
      overview:
        'Short film made with the help of the Sundance Film Institute and serving as a proof-of-concept for the subsequent feature film.',
      popularity: 8.207,
      poster_path: '/xiPVdfcSO5P5wQcSzAwtMwBlvJ6.jpg',
      release_date: '1991-06-01',
      title: 'Reservoir Dogs',
      video: false,
      vote_average: 7.4,
      vote_count: 136,
    },
    {
      adult: false,
      backdrop_path: '/l8yf1Rfp58GGjt39R2jpo8nEshF.jpg',
      genre_ids: [35, 10751, 28, 14, 12, 9648],
      id: '39691',
      original_language: 'en',
      original_title: 'Cats & Dogs: The Revenge of Kitty Galore',
      overview:
        'The ongoing war between the canine and feline species is put on hold when they join forces to thwart a rogue cat spy with her own sinister plans for conquest.',
      popularity: 27.22,
      poster_path: '/nTsZT66I4U3aS9ezLdOKacfvo8T.jpg',
      release_date: '2010-07-28',
      title: 'Cats & Dogs: The Revenge of Kitty Galore',
      video: false,
      vote_average: 5.2,
      vote_count: 520,
    },
    {
      adult: false,
      backdrop_path: '/6PkzgNLKoK1Oy0j7L79JuBgl22r.jpg',
      genre_ids: [18, 36],
      id: '8588',
      original_language: 'en',
      original_title: 'Shooting Dogs',
      overview:
        'Two westerners, a priest and a teacher find themselves in the middle of the Rwandan genocide and face a moral dilemna. Do they place themselves in danger and protect the refugees, or escape the country with their lives? Based on a true story.',
      popularity: 6.213,
      poster_path: '/9xC2yUgqPVvoHykYuigrxLyunya.jpg',
      release_date: '2006-03-08',
      title: 'Shooting Dogs',
      video: false,
      vote_average: 7.5,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: '/kqkYa0ou7qRur7qb3QBfQkDA8wc.jpg',
      genre_ids: [10749, 35],
      id: '11648',
      original_language: 'en',
      original_title: 'Must Love Dogs',
      overview:
        "Sarah Nolan is a newly divorced woman cautiously rediscovering romance with the enthusiastic but often misguided help of her well-meaning family. As she braves a series of hilarious disastrous mismatches and first dates, Sarah begins to trust her own instincts again and learns that, no matter what, it's never a good idea to give up on love.",
      popularity: 10.667,
      poster_path: '/252PdRj3y2S05DC4oSf2qk2vva3.jpg',
      release_date: '2005-07-21',
      title: 'Must Love Dogs',
      video: false,
      vote_average: 5.9,
      vote_count: 393,
    },
    {
      adult: false,
      backdrop_path: '/bfZrLxmHh7jAvTJcnj5FX5J9yIW.jpg',
      genre_ids: [18, 35],
      id: '403068',
      original_language: 'en',
      original_title: 'Sun Dogs',
      overview:
        'A man eager to serve his country but rejected by the Marines pairs up with a young runaway to form an unlikely team on a misguided adventure.',
      popularity: 6.614,
      poster_path: '/hiEHsguMwMyZMRXgjgQaB2Vpbzj.jpg',
      release_date: '2017-06-18',
      title: 'Sun Dogs',
      video: false,
      vote_average: 6.8,
      vote_count: 75,
    },
    {
      adult: false,
      backdrop_path: '/tebcp0UUNmLui8kHhqozp3TmEqq.jpg',
      genre_ids: [35, 10749, 10770],
      id: '298317',
      original_language: 'en',
      original_title: "My Boyfriends' Dogs",
      overview:
        "The owners of a small diner are surprised one rainy evening when, just after close, a young woman wearing a wedding dress with three dogs in tow begs to come into their restaurant. What follows is the young woman's retelling of how she arrived at this curious junction in her life and how, through the search for the right man, she ended up as a runaway bride with three new dogs.",
      popularity: 6.479,
      poster_path: '/ffNqpSglkigE2eIVFGSXUYihFCN.jpg',
      release_date: '2014-10-18',
      title: "My Boyfriends' Dogs",
      video: false,
      vote_average: 6,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: '/6V5Jui7BiMHMr1ZIFmiFzefCzjd.jpg',
      genre_ids: [18, 16, 10751, 35, 14],
      id: '11497',
      original_language: 'en',
      original_title: 'All Dogs Go to Heaven',
      overview:
        "When a casino owning dog named Charlie is murdered by his rival Carface, he finds himself in Heaven basically by default since all dogs go to heaven. However, since he wants to get back at his killer, he cons his way back to the living with the warning that doing that damns him to Hell. Once back, he teams with his old partner, Itchy to prep his retaliation. He also stumbles on to an orphan girl who can talk to the animals, thus allowing him to get the inside info on the races to ensure his wins to finance his plans. However, all the while, he is still haunted by nightmares on what's waiting for him on the other side unless he can prove that he is worthy of Heaven again.",
      popularity: 16.63,
      poster_path: '/nmWh1NglDinfkHD9zCNqGWyhl7Q.jpg',
      release_date: '1989-11-17',
      title: 'All Dogs Go to Heaven',
      video: false,
      vote_average: 6.7,
      vote_count: 827,
    },
  ] as MovieItem[],
} as PaginatedMovieResponse;

export const PAGES = [buildPageData(1), buildPageData(2), buildPageData(3), buildPageData(4)];

function buildPageData(page: number, perPage = 10): PaginatedMovieResponse {
  const start = (page - 1) * perPage;
  const end = start + perPage - 1;
  return {
    pagination: { total: 20, perPage, lastPage: Math.ceil(20 / perPage), currentPage: page, start, end },
    list: PAGINATED_RESPONSE.list.slice(start, end),
  };
}

export const GENRES = {
  genres: [
    { id: '28', name: 'Action' },
    { id: '12', name: 'Adventure' },
    { id: '16', name: 'Animation' },
    { id: '35', name: 'Comedy' },
    { id: '80', name: 'Crime' },
    { id: '99', name: 'Documentary' },
    { id: '18', name: 'Drama' },
    { id: '10751', name: 'Family' },
    { id: '14', name: 'Fantasy' },
    { id: '36', name: 'History' },
    { id: '27', name: 'Horror' },
    { id: '10402', name: 'Music' },
    { id: '9648', name: 'Mystery' },
    { id: '10749', name: 'Romance' },
    { id: '878', name: 'Science Fiction' },
    { id: '10770', name: 'TV Movie' },
    { id: '53', name: 'Thriller' },
    { id: '10752', name: 'War' },
    { id: '37', name: 'Western' },
  ],
};
